### ISSUE TITLE
Internal Torch Dynamo Error

### ISSUE THREAD

**Issue by reginald-mclean** [pytorch-labs/LeanRL#10]
Hello! 

Thanks for the cool project. I am looking to extend it to an upcoming Multi-Task RL project. I am having trouble running the ppo_atari_envpool_torchcompile.py file. I can run the file with either cudagraphs or compile, but not both. The full trace & output when running this file with `python leanrl/ppo_atari_envpool_torchcompile.py     --seed 1     --compile     --cudagraphs`

```shell
/home/reggiemclean/miniconda3/envs/leanrl/lib/python3.10/site-packages/tensordict/nn/cudagraphs.py:194: UserWarning: Tensordict is registered in PyTree. This is incompatible with CudaGraphModule. Removing TDs from PyTree. To silence this warning, call tensordict.nn.functional_module._exclude_td_from_pytree().set() or set the environment variable `EXCLUDE_TD_FROM_PYTREE=1`. This operation is irreversible.
  warnings.warn(
  0%|                                                                                                                                                                                                  | 0/9765 [00:00<?, ?it/s]W1007 16:50:26.820000 1095604 site-packages/torch/_logging/_internal.py:1080] [12/0] Profiler function <class 'torch.autograd.profiler.record_function'> will be ignored
  0%|                                                                                                                                                                                       | 1/9765 [00:07<21:00:43,  7.75s/it]/home/reggiemclean/miniconda3/envs/leanrl/lib/python3.10/site-packages/torch/cuda/graphs.py:84: UserWarning: The CUDA Graph is empty. This usually means that the graph was attempted to be captured on wrong device or stream. (Triggered internally at ../aten/src/ATen/cuda/CUDAGraph.cpp:208.)
  super().capture_end()
  0%|                                                                                                                                                                                       | 1/9765 [00:08<22:22:05,  8.25s/it]
Traceback (most recent call last):
  File "/home/reggiemclean/LeanRL/leanrl/ppo_atari_envpool_torchcompile.py", line 380, in <module>
    container = gae(next_obs, next_done, container)
  File "/home/reggiemclean/miniconda3/envs/leanrl/lib/python3.10/site-packages/tensordict/nn/cudagraphs.py", line 406, in __call__
    return self._call_func(*args, **kwargs)
  File "/home/reggiemclean/miniconda3/envs/leanrl/lib/python3.10/site-packages/tensordict/nn/cudagraphs.py", line 335, in _call
    out = self.module(*self._args, **self._kwargs)
  File "/home/reggiemclean/miniconda3/envs/leanrl/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py", line 462, in _fn
    return fn(*args, **kwargs)
  File "/home/reggiemclean/miniconda3/envs/leanrl/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 1335, in __call__
    return self._torchdynamo_orig_callable(
  File "/home/reggiemclean/miniconda3/envs/leanrl/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 528, in __call__
    return _compile(
  File "/home/reggiemclean/miniconda3/envs/leanrl/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 985, in _compile
    raise InternalTorchDynamoError(
  File "/home/reggiemclean/miniconda3/envs/leanrl/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 948, in _compile
    guarded_code = compile_inner(code, one_graph, hooks, transform)
  File "/home/reggiemclean/miniconda3/envs/leanrl/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 679, in compile_inner
    return _compile_inner(code, one_graph, hooks, transform)
  File "/home/reggiemclean/miniconda3/envs/leanrl/lib/python3.10/site-packages/torch/_utils_internal.py", line 87, in wrapper_function
    return function(*args, **kwargs)
  File "/home/reggiemclean/miniconda3/envs/leanrl/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 712, in _compile_inner
    out_code = transform_code_object(code, transform)
  File "/home/reggiemclean/miniconda3/envs/leanrl/lib/python3.10/site-packages/torch/_dynamo/bytecode_transformation.py", line 1337, in transform_code_object
    transformations(instructions, code_options)
  File "/home/reggiemclean/miniconda3/envs/leanrl/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 210, in _fn
    cuda_rng_state = torch.cuda.get_rng_state()
  File "/home/reggiemclean/miniconda3/envs/leanrl/lib/python3.10/site-packages/torch/cuda/random.py", line 42, in get_rng_state
    return default_generator.get_state()
torch._dynamo.exc.InternalTorchDynamoError: RuntimeError: Cannot call CUDAGeneratorImpl::current_seed during CUDA graph capture. If you need this call to be captured, please file an issue. Current cudaStreamCaptureStatus: cudaStreamCaptureStatusActive


You can suppress this exception and fall back to eager by setting:
    import torch._dynamo
    torch._dynamo.config.suppress_errors = True
```

**Comment by reginald-mclean** [comment]
It seems that right now (at least in my setup) the gae module can't be wrapped in a CudaGraphModule.
From the above error message `container = gae(next_obs, next_done, container)` therefore if I comment out 
`gae = CudaGraphModule(gae)` inside `if args.cudagraphs' I can get ~3.2k SPS on a 3090 & Ryzen 5950x.

**Comment by roger-creus** [comment]
same issue here!

**Comment by vmoens** [comment]
#11 should solve this issue!
